# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(blank=True, null=True, verbose_name='Ordinal')),
                ('votes', models.IntegerField(blank=True, help_text='How many people voted for this candidate', null=True, verbose_name='Elected by #')),
                ('status', models.CharField(choices=[('S', b'Verification process started'), ('V', b'Verified'), ('X', b'Illegal')], default=b'S', max_length=1)),
                ('for_mayor', models.BooleanField(default=False, verbose_name='Mayorship candidate')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='List Name')),
                ('ballot', models.CharField(max_length=5, verbose_name='Ballot')),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('homepage_url', models.URLField(blank=True, null=True, verbose_name='Homepage URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('platform', models.TextField(blank=True, null=True, verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('accepts_memberships', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
    ]
