# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('entities', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelist',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, through='user.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='surplus_partner',
            field=models.ForeignKey(blank=True, help_text='The list with which is the surplus votes partner', null=True, on_delete=django.db.models.deletion.CASCADE, to='polyorg.CandidateList'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyorg.CandidateList', verbose_name='candidate list'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polyorg.Party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
