# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import entities.models
import slugify


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified')),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Model the domain structure by positioning this division relative to others. 0 is the highest level. Divisions of equivalent level  should have an equal value.', verbose_name='Index')),
                ('name', models.CharField(db_index=True, help_text='The name of this division. Divisions under the same Domain must be named uniquely.', max_length=255, verbose_name='Name')),
                ('budgeting', models.BooleanField(db_index=True, default=False, help_text='Indicates whether entities that belong to this division are budgeting entities.', verbose_name='Budgeting')),
            ],
            options={
                'verbose_name_plural': 'divisions',
                'verbose_name': 'division',
                'ordering': ['index', 'name'],
            },
            bases=(models.Model, entities.models.ClassMethodMixin),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified')),
                ('name', models.CharField(db_index=True, help_text='The name of this domain.', max_length=255, unique=True, verbose_name='Name')),
                ('measurement_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', help_text='The applicable measurement unit for this domain.', max_length=8, verbose_name='Measurement System')),
                ('ground_surface_unit', models.CharField(choices=[('default', 'Default'), ('dunams', 'Dunams')], default='default', help_text='Rarely to be touched, this field is for countries, like Israel, that use special units for measuring ground.', max_length=25, verbose_name='Ground Surface Unit')),
                ('currency', models.CharField(choices=[('usd', '&#36;'), ('ils', '&#8362;')], default='usd', help_text='The currency used for budgeting in this domain.', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ['name'],
            },
            bases=(models.Model, entities.models.ClassMethodMixin),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified')),
                ('name', models.CharField(db_index=True, help_text='The name of this entity.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='A short text for this entity, useful as an overview.', verbose_name='Description')),
                ('code', models.CharField(blank=True, help_text='An identifying code for this entity.', max_length=25, verbose_name='Code')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=slugify.slugify, unique=True)),
                ('division', models.ForeignKey(help_text='The division that this entity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='entities.Division')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.Entity')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'verbose_name': 'entity',
                'ordering': ('division__domain', 'division__index', 'name'),
            },
            bases=(models.Model, entities.models.ClassMethodMixin),
        ),
        migrations.AddField(
            model_name='division',
            name='domain',
            field=models.ForeignKey(help_text='The domain that this division belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='entities.Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('name', 'parent', 'division')]),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'domain')]),
        ),
    ]
