# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name=b'URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('object_pk', models.TextField(verbose_name='object ID')),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_link', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ['-link_type__importance'],
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='LinkedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=1000, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('link_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(b'link_files_storage'), upload_to=b'link_files')),
                ('link', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Link')),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('image', models.ImageField(upload_to=b'icons')),
                ('importance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'link type',
                'verbose_name_plural': 'link types',
            },
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.LinkType'),
        ),
    ]
