# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('can_answer', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('member_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polyorg.CandidateList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_notification', models.CharField(blank=True, choices=[('N', 'No Email'), ('D', 'Daily'), ('W', 'Weekly')], default=b'D', max_length=1, null=True)),
                ('avatar_uri', models.URLField(blank=True, null=True)),
                ('last_email_update', models.DateTimeField(default=datetime.datetime(1970, 8, 6, 0, 0))),
                ('verification', models.CharField(choices=[('0', b'No verification needed'), ('S', b'Verification process started'), ('V', b'Verified')], default=b'0', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
